"""Add location column to users table

Revision ID: 13457154029b
Revises: 482ba9f11ab6
Create Date: 2024-08-04 11:44:02.993498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13457154029b'
down_revision = '482ba9f11ab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
