"""Add education, location, and update experience fields to User model

Revision ID: 302a65e4eb4e
Revises: 4b5079ca99f0
Create Date: 2024-08-12 01:50:24.988556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302a65e4eb4e'
down_revision = '4b5079ca99f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('education', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.alter_column('skills',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('experience',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('experience',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('skills',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('location')
        batch_op.drop_column('education')

    # ### end Alembic commands ###
