"""Update budget to Numeric for job_postings

Revision ID: 5fcff0a223fe
Revises: 482ba9f11ab6
Create Date: 2024-08-03 18:19:11.606977

"""
from alembic import op
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5fcff0a223fe'
down_revision = '482ba9f11ab6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        # Add 'budget' column without NOT NULL constraint
        batch_op.add_column(sa.Column('budget', sa.Numeric(precision=10, scale=2), nullable=True))
        # Add other columns
        batch_op.add_column(sa.Column('experience_level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=200), nullable=True))

    # Update existing rows to provide a default value for 'budget'
    op.execute('UPDATE job_postings SET budget = 0.00 WHERE budget IS NULL')

    # Alter 'budget' column to set NOT NULL constraint
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.alter_column('budget', existing_type=sa.Numeric(precision=10, scale=2), nullable=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        # Remove columns
        batch_op.drop_column('location')
        batch_op.drop_column('experience_level')
        # Alter 'budget' column to make it nullable again before dropping
        batch_op.alter_column('budget', existing_type=sa.Numeric(precision=10, scale=2), nullable=True)
        batch_op.drop_column('budget')

    # ### end Alembic commands ###

