"""fields

Revision ID: 992b9b1285c9
Revises: 43d461d7e6e7
Create Date: 2024-08-04 11:54:07.668936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '992b9b1285c9'
down_revision = '43d461d7e6e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('min_salary', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('max_salary', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('salary_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('education', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('experience', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('job_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('vacancies', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('expiration_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('job_level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('responsibilities', sa.Text(), nullable=True))
        batch_op.alter_column('budget',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.alter_column('budget',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.drop_column('responsibilities')
        batch_op.drop_column('job_level')
        batch_op.drop_column('expiration_date')
        batch_op.drop_column('vacancies')
        batch_op.drop_column('job_type')
        batch_op.drop_column('experience')
        batch_op.drop_column('education')
        batch_op.drop_column('salary_type')
        batch_op.drop_column('max_salary')
        batch_op.drop_column('min_salary')
        batch_op.drop_column('role')
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
