"""Add unique constraint to AcceptedFreelancer

Revision ID: d9395fc3614a
Revises: 29455d7ac456
Create Date: 2024-08-13 00:59:43.721392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9395fc3614a'
down_revision = '29455d7ac456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accepted_freelancers', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_freelancer_client', ['freelancer_id', 'client_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accepted_freelancers', schema=None) as batch_op:
        batch_op.drop_constraint('unique_freelancer_client', type_='unique')

    # ### end Alembic commands ###
